// Comprehensive content index for the SA Transformation Fund website
import { SearchableContent } from './types';

const currentDate = new Date().toISOString().split('T')[0];

export const searchableContent: SearchableContent[] = [
  // ============================================
  // FAQs - Highest priority for direct answers
  // ============================================
  {
    id: 'faq-what-is-fund',
    type: 'faq',
    title: 'What is the Transformation Fund?',
    description: 'Government-backed initiative providing financial support to Black-owned businesses',
    content: "The Transformation Fund is a government-backed initiative designed to provide financial support to Black-owned businesses in South Africa. We offer various funding options including grants, loans, and equity investments to help entrepreneurs grow and scale their businesses.",
    url: '/faq',
    anchor: 'faq-0',
    category: 'general',
    audience: ['entrepreneurs', 'corporates', 'government', 'investors', 'general'],
    keywords: ['what is', 'transformation fund', 'about', 'overview', 'definition', 'purpose', 'mission', 'government', 'black-owned'],
    priority: 5,
    lastUpdated: currentDate,
  },
  {
    id: 'faq-eligibility',
    type: 'faq',
    title: 'What are the eligibility requirements for funding?',
    description: 'General eligibility criteria including registration, business plan, and compliance',
    content: "Eligibility varies by program, but general requirements include: South African registered business or individual, clear business plan and financial projections, compliance with regulatory requirements, demonstration of economic impact potential, and meeting specific program criteria (B-BBEE status, sector focus, etc.).",
    url: '/faq',
    anchor: 'faq-1',
    category: 'eligibility',
    audience: ['entrepreneurs', 'general'],
    keywords: ['eligibility', 'requirements', 'qualifications', 'criteria', 'who qualifies', 'B-BBEE', 'registered business'],
    priority: 5,
    lastUpdated: currentDate,
  },
  {
    id: 'faq-funding-amount',
    type: 'faq',
    title: 'How much funding can I apply for?',
    description: 'Funding ranges from R50,000 to R10 million based on business needs',
    content: "Funding amounts vary based on your business needs and eligibility. We offer support ranging from R50,000 for early-stage businesses up to R10 million for established enterprises. The exact amount will be determined during the assessment process based on your business plan and requirements.",
    url: '/faq',
    anchor: 'faq-2',
    category: 'funding',
    audience: ['entrepreneurs', 'general'],
    keywords: ['how much', 'funding amount', 'money', 'R50000', 'R10 million', 'capital', 'investment size'],
    priority: 5,
    lastUpdated: currentDate,
  },
  {
    id: 'faq-process-timeline',
    type: 'faq',
    title: 'How long does the application process take?',
    description: 'Standard applications 14-21 days, complex applications 30-45 days',
    content: "Application timelines vary by program complexity. Standard Applications take 14-21 business days for review and approval. Complex Applications take 30-45 business days for comprehensive due diligence.",
    url: '/faq',
    anchor: 'faq-3',
    category: 'application',
    audience: ['entrepreneurs', 'general'],
    keywords: ['how long', 'timeline', 'duration', 'processing time', 'turnaround', 'waiting period', 'business days'],
    priority: 5,
    lastUpdated: currentDate,
  },
  {
    id: 'faq-documents',
    type: 'faq',
    title: 'What documents do I need to apply?',
    description: 'Required business and project documentation for applications',
    content: "Required documentation typically includes business documents (company registration certificate, tax clearance certificate, B-BBEE certificate if applicable, audited financial statements) and project documents (detailed business plan, financial projections, market analysis, impact assessment).",
    url: '/faq',
    anchor: 'faq-4',
    category: 'application',
    audience: ['entrepreneurs', 'general'],
    keywords: ['documents', 'paperwork', 'requirements', 'registration', 'tax clearance', 'B-BBEE certificate', 'business plan', 'financial statements'],
    priority: 5,
    lastUpdated: currentDate,
  },
  {
    id: 'faq-early-stage',
    type: 'faq',
    title: 'Can I apply if my business is less than 12 months old?',
    description: 'Start-up Grant program available for businesses under 12 months',
    content: "Yes, we have specific funding programs for early-stage businesses. While some programs require a longer operational history, our Start-up Grant program is specifically designed for businesses under 12 months old. Check your eligibility using our quiz on the How to Apply page.",
    url: '/faq',
    anchor: 'faq-5',
    category: 'eligibility',
    audience: ['entrepreneurs', 'general'],
    keywords: ['startup', 'new business', 'early stage', 'less than 12 months', 'young business', 'start-up grant'],
    priority: 4,
    lastUpdated: currentDate,
  },
  {
    id: 'faq-support-beyond',
    type: 'faq',
    title: 'What support do you provide beyond funding?',
    description: 'Business development, mentorship, and training support',
    content: "We provide comprehensive support throughout your journey including business development (strategic planning and market research support), mentorship (access to experienced business leaders), and training (skills development and capacity building).",
    url: '/faq',
    anchor: 'faq-6',
    category: 'support',
    audience: ['entrepreneurs', 'general'],
    keywords: ['support', 'mentorship', 'training', 'business development', 'coaching', 'skills', 'capacity building'],
    priority: 4,
    lastUpdated: currentDate,
  },
  {
    id: 'faq-multiple-programs',
    type: 'faq',
    title: 'Can I apply for multiple funding programs?',
    description: 'Guidelines for applying to multiple programs simultaneously',
    content: "Yes, you can apply for multiple programs, but there are guidelines. Start with one program that best fits your current needs, then explore additional programs as your business grows. Each application is evaluated independently, funding amounts may be adjusted to prevent over-leveraging, and sequential applications often work better than simultaneous ones.",
    url: '/faq',
    anchor: 'faq-7',
    category: 'application',
    audience: ['entrepreneurs', 'general'],
    keywords: ['multiple programs', 'more than one', 'several applications', 'combine funding'],
    priority: 4,
    lastUpdated: currentDate,
  },
  {
    id: 'faq-cost',
    type: 'faq',
    title: 'Is there any cost to apply?',
    description: 'No application fees - beware of scams',
    content: "No, there is absolutely no fee to apply for funding through the Transformation Fund. Beware of any third parties claiming to charge application fees on our behalf – this is a scam.",
    url: '/faq',
    anchor: 'faq-8',
    category: 'application',
    audience: ['entrepreneurs', 'general'],
    keywords: ['cost', 'fee', 'free', 'charge', 'payment', 'scam', 'no cost'],
    priority: 4,
    lastUpdated: currentDate,
  },
  {
    id: 'faq-after-approval',
    type: 'faq',
    title: 'What happens after my application is approved?',
    description: 'Offer letter, fund disbursement, and relationship manager assignment',
    content: "Once approved, you'll receive a formal offer letter outlining the terms. After accepting, funds are typically disbursed within 2-4 weeks. You'll also be assigned a relationship manager to support you throughout your funding journey.",
    url: '/faq',
    anchor: 'faq-9',
    category: 'application',
    audience: ['entrepreneurs', 'general'],
    keywords: ['approved', 'after approval', 'next steps', 'disbursement', 'offer letter', 'relationship manager'],
    priority: 4,
    lastUpdated: currentDate,
  },
  {
    id: 'faq-declined',
    type: 'faq',
    title: 'What happens if my application is declined?',
    description: 'Feedback, reapplication support, and alternative program guidance',
    content: "We believe in supporting your success, even if your initial application isn't approved. You'll receive detailed feedback with specific reasons for decline and improvement recommendations, reapplication support with access to mentorship, guidance on alternative programs that might be a better fit, and access to development resources and training programs.",
    url: '/faq',
    anchor: 'faq-10',
    category: 'application',
    audience: ['entrepreneurs', 'general'],
    keywords: ['declined', 'rejected', 'unsuccessful', 'feedback', 'reapply', 'alternative programs'],
    priority: 4,
    lastUpdated: currentDate,
  },
  {
    id: 'faq-reapply',
    type: 'faq',
    title: 'Can I reapply if my application is rejected?',
    description: 'Reapply after 6 months with improved application',
    content: "Yes, you can reapply after 6 months. We recommend addressing the reasons for rejection before reapplying. Our team will provide feedback on your application to help you improve your chances in future applications.",
    url: '/faq',
    anchor: 'faq-11',
    category: 'application',
    audience: ['entrepreneurs', 'general'],
    keywords: ['reapply', 'resubmit', 'try again', 'rejected', '6 months', 'second chance'],
    priority: 4,
    lastUpdated: currentDate,
  },

  // ============================================
  // Policy & Governance Sections
  // ============================================
  {
    id: 'policy-choice',
    type: 'policy',
    title: 'The Policy Choice',
    description: 'Bold intervention to accelerate transformation through pooled resources',
    content: "The Transformation Fund represents a policy choice to create a bold, coordinated intervention that accelerates transformation through pooled resources and shared accountability. It addresses the fragmentation problem where multiple agencies and corporates work in isolation.",
    url: '/about/why#policy-choice',
    category: 'governance',
    audience: ['government', 'corporates', 'general'],
    keywords: ['policy', 'governance', 'intervention', 'strategy', 'approach', 'coordination', 'pooled resources'],
    priority: 4,
    lastUpdated: currentDate,
  },
  {
    id: 'policy-funding-sources',
    type: 'policy',
    title: 'Funding Sources',
    description: 'How the Fund is financed through government and corporate contributions',
    content: "Funding sources include government appropriations, development finance institutions, corporate Enterprise and Supplier Development (ED/SD) contributions, and private sector investments. This blended approach creates a substantial capital base for transformation initiatives.",
    url: '/about/why#policy-choice',
    anchor: 'funding-sources',
    category: 'funding',
    audience: ['government', 'corporates', 'investors'],
    keywords: ['funding sources', 'finance', 'money', 'capital', 'budget', 'contributions', 'government funding'],
    priority: 4,
    lastUpdated: currentDate,
  },
  {
    id: 'policy-governance',
    type: 'policy',
    title: 'Governance Structure',
    description: 'Multi-stakeholder board with government, private sector, and civil society',
    content: "The Fund is governed by a multi-stakeholder board comprising representatives from government departments, private sector partners, development finance institutions, and civil society organizations. This ensures balanced oversight and accountability.",
    url: '/about/why#policy-choice',
    anchor: 'governance-structure',
    category: 'governance',
    audience: ['government', 'corporates', 'general'],
    keywords: ['governance', 'board', 'oversight', 'management', 'structure', 'accountability', 'stakeholders'],
    priority: 4,
    lastUpdated: currentDate,
  },

  // ============================================
  // Theory of Change Sections
  // ============================================
  {
    id: 'theory-of-change',
    type: 'guide',
    title: 'Theory of Change',
    description: 'How pooling resources creates network effects and systemic impact',
    content: "The Theory of Change explains how pooling fragmented resources creates network effects that amplify impact. By coordinating capital, capability development, and market access, the Fund creates a virtuous cycle that strengthens the entire ecosystem.",
    url: '/about/why#theory',
    category: 'governance',
    audience: ['government', 'corporates', 'investors', 'general'],
    keywords: ['theory of change', 'network effects', 'systemic impact', 'pooling', 'coordination', 'ecosystem'],
    priority: 3,
    lastUpdated: currentDate,
  },

  // ============================================
  // Value Proposition Sections
  // ============================================
  {
    id: 'value-government',
    type: 'section',
    title: 'Value for Government & Policy Makers',
    description: 'How the Fund benefits government through coordinated policy implementation',
    content: "For government and policy makers, the Fund provides coordinated implementation of transformation policy, measurable outcomes through the Transformation Index, efficient deployment of public resources, and reduced fragmentation across agencies.",
    url: '/about/why#value',
    anchor: 'government',
    category: 'governance',
    audience: ['government'],
    keywords: ['government', 'policy makers', 'public sector', 'benefits', 'value proposition'],
    priority: 3,
    lastUpdated: currentDate,
  },
  {
    id: 'value-private-sector',
    type: 'section',
    title: 'Value for Private Sector & Investors',
    description: 'Benefits for corporates through enhanced B-BBEE compliance and impact',
    content: "For the private sector and investors, the Fund offers enhanced B-BBEE compliance outcomes, access to vetted investment opportunities, reduced due diligence costs through shared infrastructure, and measurable social impact for ESG reporting.",
    url: '/about/why#value',
    anchor: 'private-sector',
    category: 'funding',
    audience: ['corporates', 'investors'],
    keywords: ['private sector', 'investors', 'corporates', 'business', 'ESG', 'investment opportunities'],
    priority: 3,
    lastUpdated: currentDate,
  },
  {
    id: 'value-communities',
    type: 'section',
    title: 'Value for Labour, Communities & Society',
    description: 'Job creation, skills development, and community empowerment',
    content: "For labour, communities, and society, the Fund creates sustainable jobs, develops skills through training programs, builds local economic capacity, and promotes inclusive growth that benefits previously disadvantaged communities.",
    url: '/about/why#value',
    anchor: 'communities',
    category: 'impact',
    audience: ['general'],
    keywords: ['communities', 'society', 'jobs', 'employment', 'skills', 'training', 'empowerment'],
    priority: 3,
    lastUpdated: currentDate,
  },

  // ============================================
  // Operating Model
  // ============================================
  {
    id: 'operating-capital',
    type: 'guide',
    title: 'Access to Capital',
    description: 'Grants, loans, equity, and blended finance instruments',
    content: "Access to Capital provides various funding instruments including grants for early-stage businesses, concessional loans for growth enterprises, equity investments for scale-ups, and blended finance structures that combine public and private capital.",
    url: '/about/why#operating-model',
    anchor: 'capital',
    category: 'funding',
    audience: ['entrepreneurs', 'investors'],
    keywords: ['capital', 'funding', 'grants', 'loans', 'equity', 'blended finance', 'investment', 'money'],
    priority: 4,
    lastUpdated: currentDate,
  },
  {
    id: 'operating-capability',
    type: 'guide',
    title: 'Access to Capability',
    description: 'Business development, training, and mentorship programs',
    content: "Access to Capability provides business development support, technical training programs, mentorship from experienced entrepreneurs and executives, and digital literacy training to help businesses build sustainable operations.",
    url: '/about/why#operating-model',
    anchor: 'capability',
    category: 'support',
    audience: ['entrepreneurs', 'general'],
    keywords: ['capability', 'training', 'mentorship', 'skills', 'development', 'coaching', 'support programs'],
    priority: 4,
    lastUpdated: currentDate,
  },
  {
    id: 'operating-markets',
    type: 'guide',
    title: 'Access to Markets',
    description: 'Procurement linkages and supply chain integration opportunities',
    content: "Access to Markets connects empowered enterprises to procurement opportunities with corporates and government, facilitates supply chain integration, and provides export market support for businesses ready to scale internationally.",
    url: '/about/why#operating-model',
    anchor: 'markets',
    category: 'support',
    audience: ['entrepreneurs', 'corporates'],
    keywords: ['markets', 'procurement', 'supply chain', 'contracts', 'opportunities', 'customers', 'sales'],
    priority: 4,
    lastUpdated: currentDate,
  },

  // ============================================
  // Implementation Plan
  // ============================================
  {
    id: 'implementation-phases',
    type: 'guide',
    title: 'Implementation Plan',
    description: 'Phased rollout from pre-launch to institutionalisation',
    content: "The implementation follows four phases: Pre-Launch (stakeholder engagement and systems setup), Activation (pilot programs and initial deployments), Scale-Up (expansion across sectors and regions), and Institutionalisation (embedding transformation as standard practice).",
    url: '/about/why#implementation',
    category: 'governance',
    audience: ['government', 'corporates', 'general'],
    keywords: ['implementation', 'phases', 'rollout', 'timeline', 'plan', 'stages', 'execution'],
    priority: 3,
    lastUpdated: currentDate,
  },

  // ============================================
  // National Agenda
  // ============================================
  {
    id: 'national-agenda',
    type: 'policy',
    title: 'Advancing the National Agenda',
    description: 'Alignment with national development priorities and goals',
    content: "The Fund aligns with national development priorities including entrepreneurship and SMME development, job creation and poverty reduction, broadening black ownership and participation, and strengthening social protection and economic resilience.",
    url: '/about/why#national-agenda',
    category: 'governance',
    audience: ['government', 'general'],
    keywords: ['national agenda', 'development', 'priorities', 'goals', 'NDP', 'national development plan'],
    priority: 3,
    lastUpdated: currentDate,
  },

  // ============================================
  // About Page Content
  // ============================================
  {
    id: 'about-vision',
    type: 'section',
    title: 'Building the Future - Our Vision',
    description: 'Creating a transformed economy with broad-based participation',
    content: "Our vision is a transformed South African economy where black-owned businesses thrive, create jobs, and participate meaningfully in all sectors. We envision an ecosystem where transformation is not just compliance but competitive advantage.",
    url: '/about#vision',
    category: 'general',
    audience: ['general'],
    keywords: ['vision', 'future', 'mission', 'goals', 'purpose', 'about us'],
    priority: 3,
    lastUpdated: currentDate,
  },
  {
    id: 'about-approach',
    type: 'section',
    title: 'More Than Growth - Our Approach',
    description: 'Holistic support combining capital, capability, and market access',
    content: "Our approach goes beyond just providing capital. We bundle financial support with capability development and market access to create sustainable businesses that can compete and grow in the mainstream economy.",
    url: '/about#approach',
    category: 'support',
    audience: ['entrepreneurs', 'general'],
    keywords: ['approach', 'methodology', 'how we work', 'support model', 'holistic'],
    priority: 3,
    lastUpdated: currentDate,
  },

  // ============================================
  // Success Stories
  // ============================================
  {
    id: 'story-thandi',
    type: 'story',
    title: "Thandi's Journey - From Township to Tech Success",
    description: 'How a young entrepreneur built a successful tech company with Fund support',
    content: "Thandi started with a small coding bootcamp in Soweto and grew it into a national tech training company. With support from the Transformation Fund, she secured contracts with major corporates and now employs over 50 people.",
    url: '/news-media',
    category: 'impact',
    audience: ['entrepreneurs', 'general'],
    keywords: ['success story', 'thandi', 'tech', 'entrepreneur', 'township', 'impact', 'case study'],
    priority: 4,
    lastUpdated: currentDate,
  },
  {
    id: 'story-thabo',
    type: 'story',
    title: "Thabo's Story - Manufacturing Excellence",
    description: 'Building a manufacturing business from the ground up',
    content: "Thabo transformed a small welding workshop into a certified manufacturing supplier for the automotive industry. The Fund provided equipment financing and supplier development support, enabling him to meet quality standards and secure long-term contracts.",
    url: '/news-media',
    category: 'impact',
    audience: ['entrepreneurs', 'corporates', 'general'],
    keywords: ['success story', 'thabo', 'manufacturing', 'supplier', 'automotive', 'impact', 'case study'],
    priority: 4,
    lastUpdated: currentDate,
  },

  // ============================================
  // Contact Information
  // ============================================
  {
    id: 'contact-info',
    type: 'contact',
    title: 'Contact the Transformation Fund',
    description: 'Email, phone, and office location',
    content: "Contact us at info@sa-transformationfund.co.za or call +27 (0) 10 023 5916. Our offices are located in Johannesburg. Office hours are Monday to Friday, 8:00 AM to 5:00 PM.",
    url: '/contacts',
    category: 'contact',
    audience: ['general'],
    keywords: ['contact', 'email', 'phone', 'address', 'location', 'office', 'get in touch', 'reach us'],
    priority: 5,
    lastUpdated: currentDate,
  },
  {
    id: 'portal-login',
    type: 'guide',
    title: 'Portal Login',
    description: 'Access the online application portal',
    content: "Access the Transformation Fund online portal at online.sa-transformationfund.co.za to submit applications, track your application status, and manage your account.",
    url: 'https://dev-online.sa-transformationfund.co.za/',
    category: 'application',
    audience: ['entrepreneurs', 'general'],
    keywords: ['portal', 'login', 'sign in', 'account', 'application portal', 'online'],
    priority: 4,
    lastUpdated: currentDate,
  },

  // ============================================
  // Documents & Downloads
  // ============================================
  {
    id: 'doc-executive-summary',
    type: 'document',
    title: 'Transformation Fund Executive Summary',
    description: 'Quick overview of the Fund - PDF download',
    content: "Download the Executive Summary for a concise overview of the Transformation Fund objectives, operating model, and impact metrics. PDF document.",
    url: '/resources/Transformation_Fund_Executive_Summary_v1_29Sept.pdf',
    category: 'general',
    audience: ['general'],
    keywords: ['executive summary', 'download', 'PDF', 'overview', 'document', 'summary', 'quick guide'],
    priority: 5,
    lastUpdated: currentDate,
  },
  {
    id: 'doc-full-document',
    type: 'document',
    title: 'Full Transformation Fund Document',
    description: 'Comprehensive Fund documentation - PDF download',
    content: "Download the complete Transformation Fund document with detailed governance, funding mechanisms, eligibility criteria, and implementation plans. PDF document.",
    url: '/resources/TransformationFundDocument_v2.4_28Sept25.pdf',
    category: 'general',
    audience: ['general'],
    keywords: ['full document', 'download', 'PDF', 'comprehensive', 'detailed', 'complete', 'documentation'],
    priority: 5,
    lastUpdated: currentDate,
  },

  // ============================================
  // News & Stories page
  // ============================================
  {
    id: 'news-stories-page',
    type: 'section',
    title: 'News & Stories',
    description: 'Latest news highlights and featured success stories',
    content: "Browse the latest news, media coverage, and inspiring success stories from the Transformation Fund. Stay up to date with announcements, events, and entrepreneur spotlights.",
    url: '/news-media',
    category: 'general',
    audience: ['general', 'entrepreneurs', 'corporates', 'investors'],
    keywords: ['news', 'stories', 'media', 'announcements', 'press', 'coverage', 'highlights', 'updates'],
    priority: 4,
    lastUpdated: currentDate,
  },

  // ============================================
  // Resources & Support
  // ============================================
  {
    id: 'resource-business-development',
    type: 'guide',
    title: 'Business Development Resources',
    description: 'Access to business planning, market research, and strategic development',
    content: 'Access business planning support, market research tools, and strategic development resources. Get help with developing your business strategy, understanding your market, and planning for growth.',
    url: '/about#approach',
    category: 'support',
    audience: ['entrepreneurs', 'general'],
    keywords: ['business development', 'planning', 'market research', 'strategy', 'resources', 'support'],
    priority: 4,
    lastUpdated: currentDate,
  },
  {
    id: 'resource-mentorship',
    type: 'guide',
    title: 'Mentorship Network',
    description: 'Connect with experienced business leaders and industry experts',
    content: 'Connect with our network of experienced business leaders and industry experts for guidance and support. Get matched with mentors who can help you navigate challenges and accelerate your growth.',
    url: '/about#approach',
    category: 'support',
    audience: ['entrepreneurs', 'general'],
    keywords: ['mentorship', 'mentor', 'coaching', 'guidance', 'experts', 'leaders', 'network', 'support'],
    priority: 4,
    lastUpdated: currentDate,
  },
  {
    id: 'resource-training',
    type: 'guide',
    title: 'Training Programs',
    description: 'Skills development workshops and business management training',
    content: 'Access skills development workshops, financial literacy programs, and business management training. Build the capabilities you need to run a successful business.',
    url: '/about#approach',
    category: 'support',
    audience: ['entrepreneurs', 'general'],
    keywords: ['training', 'workshops', 'skills', 'financial literacy', 'business management', 'development', 'programs'],
    priority: 4,
    lastUpdated: currentDate,
  },

  // ============================================
  // Eligibility Criteria (7 items from /eligibility)
  // ============================================
  {
    id: 'eligibility-informal',
    type: 'section',
    title: 'Informal and start-up enterprises',
    description: 'Township traders, emerging farmers, and micro manufacturers needing support to formalise',
    content: 'Includes township traders, emerging farmers, and micro manufacturers needing support to formalise and grow. These greenfield ventures often lie outside formal supply chains and lack access to capital.',
    url: '/eligibility',
    anchor: 'eligibility-criteria',
    category: 'eligibility',
    audience: ['entrepreneurs', 'general'],
    keywords: ['informal', 'startup', 'township traders', 'emerging farmers', 'micro manufacturers', 'formalise', 'greenfield'],
    priority: 4,
    lastUpdated: currentDate,
  },
  {
    id: 'eligibility-early-stage',
    type: 'section',
    title: 'Early-stage industrial and high-impact ventures',
    description: 'Black Industrialist projects in manufacturing, agro-processing, mineral beneficiation, green economy',
    content: 'Targets Black Industrialist projects and strategic sectors such as manufacturing, agro-processing, mineral beneficiation, and green economy. These ventures require patient, risk-tolerant capital to scale.',
    url: '/eligibility',
    anchor: 'eligibility-criteria',
    category: 'eligibility',
    audience: ['entrepreneurs', 'general'],
    keywords: ['early-stage', 'industrial', 'black industrialist', 'manufacturing', 'agro-processing', 'mineral beneficiation', 'green economy'],
    priority: 4,
    lastUpdated: currentDate,
  },
  {
    id: 'eligibility-growth-msme',
    type: 'section',
    title: 'Growth-phase MSMEs',
    description: 'Small and medium enterprises ready to expand but facing finance barriers',
    content: 'Supports small and medium enterprises that have survived initial hurdles and are ready to expand, but face barriers accessing conventional finance due to collateral or paperwork requirements.',
    url: '/eligibility',
    anchor: 'eligibility-criteria',
    category: 'eligibility',
    audience: ['entrepreneurs', 'general'],
    keywords: ['growth', 'MSME', 'SME', 'small business', 'medium enterprise', 'expand', 'collateral', 'finance barriers'],
    priority: 4,
    lastUpdated: currentDate,
  },
  {
    id: 'eligibility-mid-size',
    type: 'section',
    title: 'Mid-size firms graduating to large enterprises',
    description: 'Majority Black-owned firms aiming for structural growth through technology and M&A',
    content: 'Backs majority Black-owned firms with proven unit economics aiming for structural growth through technology upgrades, M&A, and market expansion, while preserving Black ownership.',
    url: '/eligibility',
    anchor: 'eligibility-criteria',
    category: 'eligibility',
    audience: ['entrepreneurs', 'corporates'],
    keywords: ['mid-size', 'large enterprise', 'black-owned', 'technology', 'M&A', 'market expansion', 'growth'],
    priority: 4,
    lastUpdated: currentDate,
  },
  {
    id: 'eligibility-cooperatives',
    type: 'section',
    title: 'Cooperatives and collective enterprises',
    description: 'Community-owned entities including agricultural cooperatives and village savings groups',
    content: 'Includes community-owned entities such as agricultural cooperatives and village savings groups, especially in rural and township areas. Support will be tailored to help them scale and access larger markets.',
    url: '/eligibility',
    anchor: 'eligibility-criteria',
    category: 'eligibility',
    audience: ['entrepreneurs', 'general'],
    keywords: ['cooperatives', 'collective', 'community-owned', 'agricultural', 'village savings', 'rural', 'township'],
    priority: 4,
    lastUpdated: currentDate,
  },
  {
    id: 'eligibility-designated-groups',
    type: 'section',
    title: 'Youth-, women-, and designated group-led businesses',
    description: 'Enterprises led by black women, youth, and people with disabilities with reserved funding',
    content: 'Prioritises enterprises led by black women, youth, and people with disabilities. A mandated portion of funding is reserved for these groups, with flexible requirements and linked technical support.',
    url: '/eligibility',
    anchor: 'eligibility-criteria',
    category: 'eligibility',
    audience: ['entrepreneurs', 'general'],
    keywords: ['youth', 'women', 'designated groups', 'disabilities', 'reserved funding', 'flexible requirements'],
    priority: 5,
    lastUpdated: currentDate,
  },
  {
    id: 'eligibility-township-rural',
    type: 'section',
    title: 'Township and rural enterprises',
    description: 'Businesses in disadvantaged geographies with dedicated funding and on-site support',
    content: 'Special emphasis is placed on businesses located in disadvantaged geographies. Dedicated funding and on-site support will help overcome infrastructure and market access barriers.',
    url: '/eligibility',
    anchor: 'eligibility-criteria',
    category: 'eligibility',
    audience: ['entrepreneurs', 'general'],
    keywords: ['township', 'rural', 'disadvantaged', 'on-site support', 'infrastructure', 'market access'],
    priority: 4,
    lastUpdated: currentDate,
  },

  // ============================================
  // Products (4 items from /eligibility/products)
  // ============================================
  {
    id: 'product-startup-grants',
    type: 'guide',
    title: 'Startup and informal business grants (capability vouchers)',
    description: 'Seed capital for early-stage and informal enterprises disbursed in milestone-linked tranches',
    content: 'Provide seed capital to early-stage and informal enterprises, disbursed in tranches tied to developmental milestones. These grants are easy to access and embedded with technical support to ensure effective use and business formalisation.',
    url: '/eligibility/products',
    category: 'funding',
    audience: ['entrepreneurs', 'general'],
    keywords: ['startup grants', 'seed capital', 'capability vouchers', 'informal business', 'milestones', 'early-stage'],
    priority: 5,
    lastUpdated: currentDate,
  },
  {
    id: 'product-growth-loans',
    type: 'guide',
    title: 'Growth and expansion loans (performance-based debt)',
    description: 'Patient concessionary finance for established MSMEs ready to scale',
    content: 'Offer patient, concessionary finance to established MSMEs ready to scale. Structured around operational performance rather than rigid collateral requirements, these loans are released in stages linked to capability improvements and business outcomes, with mentorship and monitoring built in.',
    url: '/eligibility/products',
    category: 'funding',
    audience: ['entrepreneurs', 'general'],
    keywords: ['growth loans', 'expansion', 'concessionary finance', 'performance-based', 'MSME', 'scale'],
    priority: 5,
    lastUpdated: currentDate,
  },
  {
    id: 'product-equity',
    type: 'guide',
    title: 'Equity and co-investment instruments',
    description: 'Ownership capital for high-growth ventures and strategic industrial projects',
    content: 'Provide ownership capital to high-growth ventures and strategic industrial projects, particularly those led by Black entrepreneurs. These instruments allow the Fund to take equity stakes, co-invest with private partners, and structure broad-based ownership models that include communities and workers.',
    url: '/eligibility/products',
    category: 'funding',
    audience: ['entrepreneurs', 'investors'],
    keywords: ['equity', 'co-investment', 'ownership', 'high-growth', 'strategic', 'black entrepreneurs'],
    priority: 5,
    lastUpdated: currentDate,
  },
  {
    id: 'product-blended-finance',
    type: 'guide',
    title: 'Blended finance and guarantee instruments',
    description: 'Combining public and private capital to de-risk lending to underserved enterprises',
    content: 'Combine public and private capital to de-risk lending to underserved enterprises. These include partial credit guarantees, subsidised credit lines, and risk-sharing facilities that encourage commercial lenders to extend finance to MSMEs.',
    url: '/eligibility/products',
    category: 'funding',
    audience: ['entrepreneurs', 'investors', 'corporates'],
    keywords: ['blended finance', 'guarantees', 'de-risk', 'credit guarantees', 'risk-sharing', 'commercial lenders'],
    priority: 5,
    lastUpdated: currentDate,
  },

  // ============================================
  // Market Segments (from /eligibility/market-segments)
  // ============================================
  {
    id: 'market-ownership',
    type: 'section',
    title: 'Market Segment: Ownership',
    description: 'Support for black-owned businesses including women, youth and persons with disabilities',
    content: 'We support black-owned businesses, including enterprises owned by women, youth and persons with disabilities, with a strong emphasis on broad-based and community-linked participation.',
    url: '/eligibility/market-segments',
    category: 'eligibility',
    audience: ['entrepreneurs', 'general'],
    keywords: ['ownership', 'black-owned', 'women', 'youth', 'disabilities', 'community', 'broad-based'],
    priority: 4,
    lastUpdated: currentDate,
  },
  {
    id: 'market-geographic',
    type: 'section',
    title: 'Market Segment: Geographic Focus',
    description: 'Priority for enterprises in rural areas and townships',
    content: 'We prioritise enterprises based in rural areas and townships, recognising their potential to drive local industrial activity, job creation and inclusive development.',
    url: '/eligibility/market-segments',
    category: 'eligibility',
    audience: ['entrepreneurs', 'general'],
    keywords: ['geographic', 'rural', 'township', 'local', 'job creation', 'inclusive development'],
    priority: 4,
    lastUpdated: currentDate,
  },
  {
    id: 'market-enterprise-stage',
    type: 'section',
    title: 'Market Segment: Enterprise Stage',
    description: 'Support for both early-stage and growth-stage enterprises',
    content: 'We support both early-stage and growth-stage enterprises, providing tailored financing and support to help businesses move from concept to scale and into sustainable, competitive operations.',
    url: '/eligibility/market-segments',
    category: 'eligibility',
    audience: ['entrepreneurs', 'general'],
    keywords: ['enterprise stage', 'early-stage', 'growth-stage', 'concept to scale', 'tailored financing'],
    priority: 4,
    lastUpdated: currentDate,
  },
  {
    id: 'sector-renewable-energy',
    type: 'section',
    title: 'Priority Sector: Renewable Energy',
    description: 'Solar, wind, hydro-electric, biofuels, biomass and biogas projects',
    content: 'We support renewable and clean energy value chains, including solar, wind and hydro-electric generation, as well as biofuels, biomass and biogas projects that contribute to energy security and a low-carbon economy.',
    url: '/eligibility/market-segments',
    category: 'funding',
    audience: ['entrepreneurs', 'investors'],
    keywords: ['renewable energy', 'solar', 'wind', 'hydro', 'biofuels', 'biomass', 'clean energy', 'green'],
    priority: 4,
    lastUpdated: currentDate,
  },
  {
    id: 'sector-mining',
    type: 'section',
    title: 'Priority Sector: Mining Services',
    description: 'Mining services, mineral beneficiation and services incidental to mining',
    content: 'Our investments extend beyond extraction to include mining services, mineral beneficiation and services incidental to mining, strengthening local value addition and industrial capability.',
    url: '/eligibility/market-segments',
    category: 'funding',
    audience: ['entrepreneurs', 'investors'],
    keywords: ['mining', 'mineral beneficiation', 'extraction', 'value addition', 'industrial'],
    priority: 4,
    lastUpdated: currentDate,
  },
  {
    id: 'sector-agro-processing',
    type: 'section',
    title: 'Priority Sector: Agro-processing',
    description: 'Food manufacturing, chemicals processing and biofuels',
    content: 'We prioritise agro-processing and food manufacturing, alongside chemicals processing and biofuels, to deepen local production, improve food security and expand export-ready industries.',
    url: '/eligibility/market-segments',
    category: 'funding',
    audience: ['entrepreneurs', 'investors'],
    keywords: ['agro-processing', 'food manufacturing', 'chemicals', 'food security', 'export'],
    priority: 4,
    lastUpdated: currentDate,
  },
  {
    id: 'sector-ict',
    type: 'section',
    title: 'Priority Sector: Information & Communication Technology',
    description: 'ICT and telecoms infrastructure for digital connectivity and innovation',
    content: 'The Transformation Fund supports the development and expansion of ICT and telecoms infrastructure that enables digital connectivity, innovation and inclusive participation in the digital economy.',
    url: '/eligibility/market-segments',
    category: 'funding',
    audience: ['entrepreneurs', 'investors'],
    keywords: ['ICT', 'technology', 'telecoms', 'digital', 'connectivity', 'innovation'],
    priority: 4,
    lastUpdated: currentDate,
  },
  {
    id: 'sector-infrastructure',
    type: 'section',
    title: 'Priority Sector: Infrastructure',
    description: 'Tourism infrastructure, bulk services and specialised buildings',
    content: 'The Transformation Fund invests in enabling infrastructure, including tourism infrastructure, bulk services and other specialised buildings that support productive economic activity.',
    url: '/eligibility/market-segments',
    category: 'funding',
    audience: ['entrepreneurs', 'investors'],
    keywords: ['infrastructure', 'tourism', 'construction', 'buildings', 'bulk services'],
    priority: 4,
    lastUpdated: currentDate,
  },
  {
    id: 'sector-manufacturing',
    type: 'section',
    title: 'Priority Sector: Manufacturing',
    description: 'Textiles, consumables, automotive components, batteries and electric accumulators',
    content: 'The Fund supports a wide range of manufacturing activities, including textiles, consumables, automotive components, batteries and electric accumulators, enabling industrial diversification and competitiveness.',
    url: '/eligibility/market-segments',
    category: 'funding',
    audience: ['entrepreneurs', 'investors'],
    keywords: ['manufacturing', 'textiles', 'automotive', 'batteries', 'industrial', 'diversification'],
    priority: 4,
    lastUpdated: currentDate,
  },
  {
    id: 'sector-services-bpo',
    type: 'section',
    title: 'Priority Sector: Services and BPO',
    description: 'Business process outsourcing, call centres, data analytics, healthcare and digital commercialisation',
    content: 'The Transformation Fund supports services-led growth through business process outsourcing, call centre and data analytics services, alongside investment in healthcare infrastructure. It also focuses on digital industry commercialisation.',
    url: '/eligibility/market-segments',
    category: 'funding',
    audience: ['entrepreneurs', 'investors'],
    keywords: ['services', 'BPO', 'call centre', 'data analytics', 'healthcare', 'digital', 'outsourcing'],
    priority: 4,
    lastUpdated: currentDate,
  },

  // ============================================
  // Funding Process (8 stages from /eligibility/process)
  // ============================================
  {
    id: 'process-stage-0',
    type: 'guide',
    title: 'Funding Process Stage 0: Initiation and sponsor alignment',
    description: 'Submit funding request, confirm sponsorship and governance arrangements',
    content: 'You start by submitting a formal funding request. At this stage, sponsorship is confirmed, governance arrangements are put in place, and the relevant regulatory pathways for your project are identified.',
    url: '/eligibility/process',
    category: 'application',
    audience: ['entrepreneurs', 'general'],
    keywords: ['initiation', 'sponsor', 'funding request', 'governance', 'regulatory', 'stage 0'],
    priority: 4,
    lastUpdated: currentDate,
  },
  {
    id: 'process-assessment',
    type: 'guide',
    title: 'Funding Process: Pre-investment assessment',
    description: 'Initial assessment of strategic alignment, readiness and potential impact',
    content: 'Your proposal is initially assessed to confirm strategic alignment, readiness and potential impact before moving into detailed development.',
    url: '/eligibility/process',
    category: 'application',
    audience: ['entrepreneurs', 'general'],
    keywords: ['assessment', 'pre-investment', 'strategic alignment', 'readiness', 'impact'],
    priority: 4,
    lastUpdated: currentDate,
  },
  {
    id: 'process-stage-1',
    type: 'guide',
    title: 'Funding Process Stage 1: Feasibility and information memorandum',
    description: 'Feasibility study, market analysis and initial financial model',
    content: 'A feasibility study and Information Memorandum are developed, setting out the project description, market analysis and an initial financial model. Proposals are reviewed by an Early Review Committee.',
    url: '/eligibility/process',
    category: 'application',
    audience: ['entrepreneurs', 'general'],
    keywords: ['feasibility', 'information memorandum', 'market analysis', 'financial model', 'stage 1'],
    priority: 4,
    lastUpdated: currentDate,
  },
  {
    id: 'process-stage-2',
    type: 'guide',
    title: 'Funding Process Stage 2: Concept, site and process design',
    description: 'Project concept refinement, site selection and technical due diligence',
    content: 'The project concept is refined through site selection, infrastructure confirmation and definition of production technology. A comprehensive concept design pack is prepared, supported by full technical, market, financial and risk due diligence.',
    url: '/eligibility/process',
    category: 'application',
    audience: ['entrepreneurs', 'general'],
    keywords: ['concept design', 'site selection', 'production technology', 'due diligence', 'stage 2'],
    priority: 3,
    lastUpdated: currentDate,
  },
  {
    id: 'process-stage-3',
    type: 'guide',
    title: 'Funding Process Stage 3: Procurement and EPC strategy',
    description: 'Equipment specifications, supplier identification and contracting',
    content: 'Equipment specifications are finalised, suppliers identified and the contracting model confirmed. Engineering, Procurement and Construction (EPC) and Technical Assistance (TA) agreements are negotiated, followed by credit approval and contracting.',
    url: '/eligibility/process',
    category: 'application',
    audience: ['entrepreneurs', 'general'],
    keywords: ['procurement', 'EPC', 'equipment', 'suppliers', 'contracting', 'stage 3'],
    priority: 3,
    lastUpdated: currentDate,
  },
  {
    id: 'process-stage-4',
    type: 'guide',
    title: 'Funding Process Stage 4: Financing and approvals',
    description: 'Capital structure finalisation, funding sources and regulatory approvals',
    content: 'The capital structure is finalised, funding sources secured and all regulatory approvals obtained. The financial model is refined, enabling disbursement and ongoing monitoring.',
    url: '/eligibility/process',
    category: 'application',
    audience: ['entrepreneurs', 'general'],
    keywords: ['financing', 'approvals', 'capital structure', 'disbursement', 'regulatory', 'stage 4'],
    priority: 3,
    lastUpdated: currentDate,
  },
  {
    id: 'process-stage-5',
    type: 'guide',
    title: 'Funding Process Stage 5: Construction and commissioning',
    description: 'Construction management with quality, health and safety standards',
    content: 'Construction and commissioning are managed in line with quality, health and safety standards. Operational and maintenance documentation is prepared to support a smooth transition to operations.',
    url: '/eligibility/process',
    category: 'application',
    audience: ['entrepreneurs', 'general'],
    keywords: ['construction', 'commissioning', 'quality', 'health and safety', 'stage 5'],
    priority: 3,
    lastUpdated: currentDate,
  },
  {
    id: 'process-stage-6',
    type: 'guide',
    title: 'Funding Process Stage 6: Operations readiness and handover',
    description: 'Operational readiness, staffing, marketing and performance KPIs',
    content: 'The final stage focuses on operational readiness, including management and staffing, establishment of marketing and distribution channels, and the setting of performance KPIs and reporting systems to ensure sustainable operations.',
    url: '/eligibility/process',
    category: 'application',
    audience: ['entrepreneurs', 'general'],
    keywords: ['operations', 'handover', 'readiness', 'staffing', 'KPIs', 'stage 6'],
    priority: 3,
    lastUpdated: currentDate,
  },

  // ============================================
  // Investors (from /investors)
  // ============================================
  {
    id: 'investor-eeip',
    type: 'section',
    title: 'Equity Equivalent Investment Programme (EEIP)',
    description: 'Multinational corporations contributing 25% of SA operations value to empowerment projects',
    content: 'Multinational corporations unable to sell equity locally can contribute 25% of their South African operations value to empowerment projects. The Fund offers a centralised vehicle for these contributions, replacing fragmented initiatives with a high-impact portfolio.',
    url: '/investors',
    category: 'funding',
    audience: ['corporates', 'investors'],
    keywords: ['EEIP', 'equity equivalent', 'multinational', 'empowerment', 'compliance', 'contributions'],
    priority: 4,
    lastUpdated: currentDate,
  },
  {
    id: 'investor-esd',
    type: 'section',
    title: 'Enterprise and Supplier Development (ESD) Contributions',
    description: 'Corporates can redirect ESD budgets into the Fund for B-BBEE recognition',
    content: 'Corporates can redirect their ESD budgets into the Fund and still receive full B-BBEE scorecard recognition. This pooled approach improves efficiency, impact, and compliance while reducing administrative burdens.',
    url: '/investors',
    category: 'funding',
    audience: ['corporates', 'investors'],
    keywords: ['ESD', 'enterprise development', 'supplier development', 'B-BBEE', 'scorecard', 'compliance'],
    priority: 4,
    lastUpdated: currentDate,
  },
  {
    id: 'investor-dfi',
    type: 'section',
    title: 'Development Finance Institutions (DFIs) and Impact Investors',
    description: 'DFIs can co-invest, offer credit lines or match-fund aligned projects',
    content: 'Domestic and international DFIs can co-invest, offer credit lines, or match-fund projects aligned with the Fund goals. Their involvement brings additional capital, technical expertise, and ESG standards.',
    url: '/investors',
    category: 'funding',
    audience: ['investors', 'government'],
    keywords: ['DFI', 'development finance', 'impact investors', 'co-invest', 'ESG', 'credit lines'],
    priority: 4,
    lastUpdated: currentDate,
  },
  {
    id: 'investor-donors',
    type: 'section',
    title: 'Donors and Philanthropy',
    description: 'Foundations and high-net-worth individuals contributing grants for targeted programmes',
    content: 'Foundations, high-net-worth individuals, and international donors can contribute grants for targeted programmes. These funds may support specific initiatives like tech accelerators or women entrepreneurship.',
    url: '/investors',
    category: 'funding',
    audience: ['investors', 'general'],
    keywords: ['donors', 'philanthropy', 'foundations', 'grants', 'women entrepreneurship', 'tech accelerators'],
    priority: 4,
    lastUpdated: currentDate,
  },
  {
    id: 'investor-innovative',
    type: 'section',
    title: 'Innovative Financing and Private Investors',
    description: 'Impact bonds, blended finance, and institutional investments like pension funds',
    content: 'As the Fund matures, it may explore impact bonds, blended finance, or institutional investments like pension funds. These instruments can offer risk-adjusted returns while supporting social impact.',
    url: '/investors',
    category: 'funding',
    audience: ['investors', 'corporates'],
    keywords: ['innovative financing', 'impact bonds', 'pension funds', 'private investors', 'risk-adjusted returns'],
    priority: 4,
    lastUpdated: currentDate,
  },

  // ============================================
  // Governance (from /investors/governance)
  // ============================================
  {
    id: 'governance-framework',
    type: 'section',
    title: 'Governance and Accountability Framework',
    description: 'SPV structure ensuring transparency, integrity, and alignment with transformation goals',
    content: 'The Transformation Fund is governed through a legally incorporated Special Purpose Vehicle (SPV), designed to ensure transparency, integrity, and alignment with national transformation goals. Its finances are ring-fenced, tax-exempt, and managed under South African law and B-BBEE regulations.',
    url: '/investors/governance',
    category: 'governance',
    audience: ['government', 'investors', 'corporates'],
    keywords: ['governance', 'accountability', 'SPV', 'transparency', 'ring-fenced', 'tax-exempt'],
    priority: 4,
    lastUpdated: currentDate,
  },
  {
    id: 'governance-board',
    type: 'section',
    title: 'Board Oversight',
    description: 'Joint Board of Directors with public and private sector representatives',
    content: 'A joint Board of Directors, comprising public and private sector representatives, will oversee the strategic direction and fiduciary responsibilities.',
    url: '/investors/governance',
    category: 'governance',
    audience: ['government', 'investors', 'corporates'],
    keywords: ['board', 'oversight', 'directors', 'fiduciary', 'strategic direction'],
    priority: 4,
    lastUpdated: currentDate,
  },
  {
    id: 'governance-digital',
    type: 'section',
    title: 'Digital Oversight',
    description: 'Real-time data collection and impact dashboard tracking key metrics',
    content: 'A central digital platform will enable real-time data collection from investees, feeding into an impact dashboard that tracks key metrics like jobs created and capital deployed. This system will support proactive management and transparent reporting.',
    url: '/investors/governance',
    category: 'governance',
    audience: ['government', 'investors'],
    keywords: ['digital oversight', 'dashboard', 'real-time', 'impact metrics', 'jobs created', 'capital deployed'],
    priority: 3,
    lastUpdated: currentDate,
  },
  {
    id: 'governance-reporting',
    type: 'section',
    title: 'Public Reporting',
    description: 'Annual integrated reports, quarterly updates, and Transformation Index',
    content: 'The Fund will publish annual integrated reports and quarterly updates, with stakeholder engagement through AGMs and parliamentary briefings. A Transformation Index will aggregate impact data for public visibility and accountability.',
    url: '/investors/governance',
    category: 'governance',
    audience: ['government', 'investors', 'general'],
    keywords: ['public reporting', 'annual reports', 'transformation index', 'AGM', 'parliamentary', 'accountability'],
    priority: 3,
    lastUpdated: currentDate,
  },

  // ============================================
  // About Page (from /about)
  // ============================================
  {
    id: 'about-objectives',
    type: 'section',
    title: 'Transformation Fund Objectives',
    description: 'Four core objectives: economic transformation, funding access, value chain participation, resource mobilisation',
    content: 'The Fund objectives are to promote economic transformation to enable meaningful participation of black people in the productive economy, improve access to funding for majority black-owned enterprises, empower enterprises to participate in value chains across key sectors, and mobilise financial resources from the private and public sector using B-BBEE legislation.',
    url: '/about',
    category: 'general',
    audience: ['general', 'entrepreneurs', 'government'],
    keywords: ['objectives', 'goals', 'economic transformation', 'black participation', 'value chains', 'B-BBEE'],
    priority: 4,
    lastUpdated: currentDate,
  },
  {
    id: 'about-method',
    type: 'section',
    title: 'The Method',
    description: 'Impact-driven approach providing capital, capabilities and market access at scale',
    content: 'The Transformation Fund adopts a deliberate, impact-driven approach that moves beyond trickle-down models and fragmented initiatives. It systematically and transparently empowers businesses at scale by providing capital, capabilities and market access, enabling firms to become self-sufficient, grow locally and globally, and create jobs.',
    url: '/about',
    category: 'general',
    audience: ['general', 'entrepreneurs', 'government'],
    keywords: ['method', 'approach', 'impact-driven', 'capital', 'capabilities', 'market access', 'scale'],
    priority: 3,
    lastUpdated: currentDate,
  },
  {
    id: 'about-architecture-capital',
    type: 'section',
    title: 'The Architecture: Capital Pillar',
    description: 'Mobilising patient, transformative capital into a professionally managed vehicle',
    content: 'The Transformation Fund will mobilise and pool patient, transformative capital from voluntary sources into a large-scale, professionally managed vehicle dedicated to expanding black-owned and community-based enterprises.',
    url: '/about',
    category: 'funding',
    audience: ['investors', 'government', 'general'],
    keywords: ['architecture', 'capital pillar', 'patient capital', 'fund-of-funds', 'SPV', 'financing gap'],
    priority: 3,
    lastUpdated: currentDate,
  },
  {
    id: 'about-architecture-capability',
    type: 'section',
    title: 'The Architecture: Capability Pillar',
    description: 'Digital-first technical assistance platform for skills, tools and systems',
    content: 'The Transformation Fund prioritises Access to Capability through a digital-first technical assistance platform providing enterprises with accounting, production and logistics tools, training and mentorship.',
    url: '/about',
    category: 'support',
    audience: ['entrepreneurs', 'general'],
    keywords: ['architecture', 'capability pillar', 'technical assistance', 'digital platform', 'training', 'mentorship'],
    priority: 3,
    lastUpdated: currentDate,
  },
  {
    id: 'about-architecture-markets',
    type: 'section',
    title: 'The Architecture: Markets Pillar',
    description: 'Unlocking market access through buyer consortia and supply chain integration',
    content: 'The Fund enables sustainable growth by unlocking reliable market access through digitally driven buyer consortia, offtake agreements, supply aggregation and integration into corporate, public and export supply chains.',
    url: '/about',
    category: 'support',
    audience: ['entrepreneurs', 'corporates'],
    keywords: ['architecture', 'markets pillar', 'buyer consortia', 'offtake', 'supply chain', 'export'],
    priority: 3,
    lastUpdated: currentDate,
  },
  {
    id: 'about-architecture-telemetry',
    type: 'section',
    title: 'The Architecture: Telemetry Pillar',
    description: 'Digital-first data-driven platform tracking performance and impact in real time',
    content: 'The Transformation Fund is built as a digital-first, data-driven platform with a comprehensive telemetry system that tracks performance and impact in real time through a Transformation Index.',
    url: '/about',
    category: 'governance',
    audience: ['government', 'investors'],
    keywords: ['architecture', 'telemetry pillar', 'data-driven', 'transformation index', 'real-time', 'performance'],
    priority: 3,
    lastUpdated: currentDate,
  },
  {
    id: 'about-architecture-governance',
    type: 'section',
    title: 'The Architecture: Governance Pillar',
    description: 'Independent board, public reporting dashboards and multi-stakeholder oversight',
    content: 'The Transformation Fund is underpinned by a strong governance framework overseen by an independent board and management team, with digitally enabled public reporting dashboards and a multi-stakeholder oversight council.',
    url: '/about',
    category: 'governance',
    audience: ['government', 'investors', 'general'],
    keywords: ['architecture', 'governance pillar', 'independent board', 'oversight council', 'public reporting'],
    priority: 3,
    lastUpdated: currentDate,
  },

  // ============================================
  // Requirements (from /requirements)
  // ============================================
  {
    id: 'requirements-general',
    type: 'guide',
    title: 'General Application Requirements',
    description: 'SA registration, tax clearance, ID, bank statements and proof of address',
    content: 'General requirements include South African registered business or individual, valid tax clearance certificate, company registration certificate, proof of identity (SA ID/passport), bank statements (last 6 months), and proof of address (not older than 3 months).',
    url: '/requirements',
    category: 'application',
    audience: ['entrepreneurs', 'general'],
    keywords: ['requirements', 'general', 'tax clearance', 'registration', 'ID', 'bank statements', 'proof of address'],
    priority: 5,
    lastUpdated: currentDate,
  },
  {
    id: 'requirements-business',
    type: 'guide',
    title: 'Business Documentation Requirements',
    description: 'Business plan, financial projections, market analysis and operational plan',
    content: 'Business documentation requirements include detailed business plan (minimum 20 pages), financial projections (3-year forecast), management accounts/financial statements, market analysis and competitive landscape, operational plan and implementation timeline, and risk assessment and mitigation strategies.',
    url: '/requirements',
    category: 'application',
    audience: ['entrepreneurs', 'general'],
    keywords: ['business plan', 'financial projections', 'market analysis', 'operational plan', 'risk assessment'],
    priority: 5,
    lastUpdated: currentDate,
  },
  {
    id: 'requirements-legal',
    type: 'guide',
    title: 'Legal & Compliance Requirements',
    description: 'B-BBEE certificate, licenses, environmental and labour compliance',
    content: 'Legal and compliance requirements include B-BBEE certificate (where applicable), industry-specific licenses and permits, environmental compliance certificates, labour relations compliance documentation, intellectual property documentation, and contracts and agreements with key suppliers/customers.',
    url: '/requirements',
    category: 'application',
    audience: ['entrepreneurs', 'general'],
    keywords: ['legal', 'compliance', 'B-BBEE certificate', 'licenses', 'permits', 'environmental', 'labour'],
    priority: 5,
    lastUpdated: currentDate,
  },
  {
    id: 'requirements-financial',
    type: 'guide',
    title: 'Financial Requirements',
    description: 'Audited statements, management accounts, cash flow projections and collateral',
    content: 'Financial requirements include audited financial statements (last 2 years), management accounts (latest month-end), cash flow projections, debt schedule and repayment capacity analysis, collateral documentation (if applicable), and use of funds breakdown and justification.',
    url: '/requirements',
    category: 'application',
    audience: ['entrepreneurs', 'general'],
    keywords: ['financial requirements', 'audited statements', 'cash flow', 'debt schedule', 'collateral', 'use of funds'],
    priority: 5,
    lastUpdated: currentDate,
  },

  // ============================================
  // Startup Grants (from /startup-grants)
  // ============================================
  {
    id: 'startup-grants-overview',
    type: 'guide',
    title: 'Startup Grants Program',
    description: 'Capability vouchers providing seed capital for early-stage and informal enterprises',
    content: 'Capability vouchers designed to provide seed capital for early-stage and informal enterprises ready to scale. Features smart instruments with small startup grants and convertible vouchers, targeting township shopkeepers, youth-led tech enterprises, and informal businesses seeking formalization. Minimal paperwork with maximum impact.',
    url: '/startup-grants',
    category: 'funding',
    audience: ['entrepreneurs', 'general'],
    keywords: ['startup grants', 'capability vouchers', 'seed capital', 'early-stage', 'informal', 'township', 'youth', 'formalization'],
    priority: 5,
    lastUpdated: currentDate,
  },

  // ============================================
  // Careers
  // ============================================
  {
    id: 'careers-page',
    type: 'section',
    title: 'Careers & Job Opportunities',
    description: 'Explore career opportunities at the Transformation Fund',
    content: 'Browse current job openings at the Transformation Fund. Find full-time, part-time, and contract positions across departments. Join our mission to support inclusive economic transformation in South Africa.',
    url: '/careers',
    category: 'general',
    audience: ['general'],
    keywords: ['careers', 'jobs', 'vacancies', 'employment', 'hiring', 'work', 'opportunities', 'positions'],
    priority: 4,
    lastUpdated: currentDate,
  },
];

// Helper function to get content by type
export const getContentByType = (type: SearchableContent['type']) => 
  searchableContent.filter(item => item.type === type);

// Helper function to get content by category
export const getContentByCategory = (category: SearchableContent['category']) => 
  searchableContent.filter(item => item.category === category);
